name: prometheus
version: 0.1
appVersion: 0.3.0
description: Polkadot Node Implementation
home: https://polkadot.network/
icon: https://polkadot.network/favicon.ico
sources:
  - https://github.com/paritytech/polkadot/
maintainers:
  - name: Paritytech Devops Team
    email: devops-team@parity.io
tillerVersion: ">=2.8.0"
