
image:
  repository: parity/polkadot
  tag: 0.2.17-ac193da
  pullPolicy: Always
  basepath: /polkadot

# see below
# replicas: 1

nodes:
  # number of external ip addresses will determine the number of replicas
  externalIPs:
    - 35.198.131.6
    - 35.242.245.237
  args:
    - --chain
    - krummelanke
    # serve rpc within the local network
    # - fenced off the world via firewall
    # - used for health checks
    - --rpc-external
    - --ws-external
    # - --log
    # - sub-libp2p=trace
    # - --validator
    # - --key
    # - key_name



# maybe adopt resource limits here to the nodes of the pool
# resources:
#   memory: "5Gi"
#   cpu: "1.5"

